name: paint

on:
  push:
    branches: ['main']
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm
          cache-dependency-path: 'meru/package-lock.json'
      - name: Install dependencies
        run: |
            cd meru
            npm i
      - name: Build static site
        env:
          BASE_PATH: '/${{ github.event.repository.name }}'
        run: |
          cd meru
          npm run build
      - name: Upload artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'meru/build/'

  deploy:
    needs: build
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
